### ISSUE TITLE
Can't build server on a clean install

### ISSUE THREAD

**Issue by hyperionjrw** [interconnectit/laravel-local-server#1]
MySQL fails to start when it tries to build from the latest image (MySQL 9) on a clean install. Had to specify mysql:8.4 image and change the command to get this to build. I don't want to step on anybody's toes, so I'm just going to leave this here for someone else to update the [YAML](https://github.com/interconnectit/laravel-local-server/blob/master/docker/docker-compose.yml)

```YAML
mysql:
        image: mysql:8.4
        container_name: ${COMPOSE_PROJECT_NAME:-default}-mysql
        command: ["mysqld", "--mysql-native-password=ON"]
```
